version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - PORT=3000
    volumes:
     - .:/starter
     - /starter/node_modules
    
    labels:
      - traefik.enable=true
      - traefik.backend=site
      - traefik.frontend.rule=Host:qitup.ca
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=proxy
      - traefik.port=3000
